services:
  myfinance_app:
    container_name: myfinance_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8006:8006"
    volumes:
      - .:/app
    env_file:
      - envs/.env